name: Test utils and endpoints

on:
  pull-request:
    branches:
      - main

jobs:
  test-utils:
    runs-on: ubuntu-latest
    steps:
      - name: Clone & Checkout Repository
        uses: actions/checkout@v3
      - name: Install Dependencies
        run: npm install
      - name: Test Util Functions
        run: npm run test-utils

